#!/usr/bin/env python
import subprocess
import requests

MY_ADDR = "IP_TO_CHECK"

def send_msg(text):
   token = "VERY_SECRET_TOKEN"
   chat_id = "CHAT_ID"
   url_req = "https://api.telegram.org/bot" + token + "/sendMessage" + "?chat_id=" + chat_id + "&text=" + text
   results = requests.get(url_req)
   print(results.json())

# check part
max_tries = 4
for _ in range(max_tries):
    command = ['ping', '-n', '-c', '10', MY_ADDR]
    proc = subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if proc.returncode == 0:
        send_msg("Host is available")
        break
    else:
        send_msg("Host is down")
